base_url = "https://www.arthurkoziel.com"

title = "Arthur Koziel"
description = "Recent Blog Posts"

author = "Arthur Koziel"
generate_feed = true
feed_filename = "feed.xml"

[markdown]
highlight_code = true
highlight_theme = "dracula"
extra_syntaxes_and_themes = ["syntaxes"]

[link_checker]
internal_level = "warn"
